### ISSUE TITLE
Can you provide pretrained models?

### ISSUE THREAD

**Issue by nvnnghia** [rytisss/RoadPavementSegmentation#1]
Thanks for sharing your great work. Can you provide your trained models?

**Comment by rytisss** [comment]
Hi,
Ofc, you can find the best weights (in .hdf5 files) here https://drive.google.com/drive/folders/1lJxyjQB3Ez1xDFhkZBW4leCI6JjCenQG?usp=sharing

**Comment by nvnnghia** [comment]
Thank you
