### ISSUE TITLE
Would you provide images and annotations for running?

### ISSUE THREAD

**Issue by randomstate4242** [rytisss/RoadPavementSegmentation#2]
Thank you for your project,

**Comment by rytisss** [comment]
Of course, you can find all the training/testing data, weights, and prediction results here: https://drive.google.com/drive/folders/1baB1T0zh4gECZgugzZ8s1QriBteu5DSz?usp=sharing

**Comment by randomstate4242** [comment]
thank you for your reply.

but Your files are probably wrong. When I download it, it cannot be
extracted.

2020년 9월 7일 (월) 오후 4:15, Rytis Augustauskas <notifications@github.com>님이 작성:

**Comment by rytisss** [comment]
Hi, i tried myself and saw that at least crackForest got corrupted while uploading into GDrive, strange. I uploaded original datasets here: [https://ktuedu-my.sharepoint.com/:u:/g/personal/rytaug_ktu_lt/EcQ_3UC22jJIj5fxCBKU7I0Ba3_Fg9zA4lxr9qq7BLJc_A?e=T1wBQi](https://ktuedu-my.sharepoint.com/:u:/g/personal/rytaug_ktu_lt/EcQ_3UC22jJIj5fxCBKU7I0Ba3_Fg9zA4lxr9qq7BLJc_A?e=T1wBQi) Although these ones are original, you need only to crop them into 320x320. I will check if I have those prepared datasets that I used for research. Im not really sure why they got corrupted...

**Comment by rytisss** [comment]
@randomstate4242 It didn't work on a tablet (with android). I just gave me an error that it is corrupted. On the laptop everything is fine, I can access data from GDrive :) Let me know if you accessed, I can upload to OneDrive
